import numpy as np


METER_SI = 1
CM_SI = 1e-2
NM_SI = 1e-9
SECOND_SI = 1
Q_E_SI = 1.60217663e-19
EV_SI = Q_E_SI
M_E_SI = 9.1093837e-31
VOLT_SI = 1
KELVIN_SI = 1
K_B_SI = 1.38064852e-23
H_BAR_SI = 1.054571817e-34  # J s
H_SI = H_BAR_SI * 2 * np.pi
EPSILON_0_SI = 8.8541878128e-12

NM = NM_SI
Q_E = Q_E_SI
EV = EV_SI
M_E = M_E_SI

DISTANCE_SCALING = NM / NM_SI
CHARGE_SCALING = Q_E / Q_E_SI
ENERGY_SCALING = EV / EV_SI
MASS_SCALING = M_E / M_E_SI
METER = METER_SI * DISTANCE_SCALING
CM = CM_SI * DISTANCE_SCALING
TIME_SCALING = np.sqrt(MASS_SCALING * DISTANCE_SCALING**2 / ENERGY_SCALING)
SECOND = SECOND_SI * TIME_SCALING
VOLTAGE_SCALING = ENERGY_SCALING / CHARGE_SCALING
VOLT = VOLT_SI * VOLTAGE_SCALING
K_B_SCALING = DISTANCE_SCALING**2 * MASS_SCALING / TIME_SCALING**2
K_B = K_B_SI * K_B_SCALING
KELVIN = KELVIN_SI * ENERGY_SCALING / K_B_SCALING
ACTION_SCALING = ENERGY_SCALING * TIME_SCALING
H_BAR = H_BAR_SI * ACTION_SCALING
H = H_SI * ACTION_SCALING
EPSILON_0 = EPSILON_0_SI * CHARGE_SCALING / VOLTAGE_SCALING / DISTANCE_SCALING
